FROM postgres:9.4

ENV GALILEO_POSTGRES_SHARED_BUFFERS=15GB
ENV GALILEO_POSTGRES_EFFECTIVE_CACHE_SIZE=43GB
ENV GALILEO_POSTGRES_WORK_MEM=16MB
ENV GALILEO_POSTGRES_MAINTENANCE_WORK_MEM=512MB
ENV GALILEO_POSTGRES_CHECKPOINT_SEGMENTS=15
ENV GALILEO_POSTGRES_RANDOM_PAGE_COST=2

ADD init-config.sh /docker-entrypoint-initdb.d

